### ISSUE TITLE
Fix statistics after deleting a round

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#10]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
Click on edit Round button and delete it.

![image](https://user-images.githubusercontent.com/32278933/93662344-14291180-fa68-11ea-9688-c81f73dc7440.png)

### Expected Behavior
Statistics is visible and updated 

### Actual Behavior
Statistics tab is empty:

![image](https://user-images.githubusercontent.com/32278933/93662349-2440f100-fa68-11ea-8a75-00c13a18f4b1.png)

**Comment by YasiOnFire** [comment]
Hi.
May I try this one?

**Comment by DavidGolodetsky** [comment]
Of course!
