### ISSUE TITLE
Log out on the Home page error in console

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#15]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
Being on the Home page, hit `Log out` button and see the console.

![image](https://user-images.githubusercontent.com/32278933/94710139-29971900-034f-11eb-9274-87b8f4bbaa51.png)

### Expected Behavior
Loging out succeed, no errors in the console.

### Actual Behavior
After hitting the button there is error in console
`Uncaught (in promise) Error: Avoided redundant navigation to current location: "/".`

**Comment by vinmaster** [comment]
Hi, can I take this one?

**Comment by DavidGolodetsky** [comment]
Sure, thanx for your help!
