### ISSUE TITLE
Reset clock count when switching between clock tabs

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#179]
Currently, when I'm changing Clock tool modal tabs the state of the clock is preserved.

https://user-images.githubusercontent.com/32278933/136669876-9b9988de-4a3a-4f8e-bc65-4f14777afd63.mov

**Expected:** when the user switching tabs clock count should be reset

**Comment by Kalingrowo** [comment]
hello, I've made a PR, you can check it if this will solve the issue
#180
