### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by faturachmanyusup** [DavidGolodetsky/GeekScore-2#18]
i use ubuntu 19.04 and Chrome Browser

**Comment by DavidGolodetsky** [comment]
hm, yes signing up is broken. Bummer, need to take a look. For now you can use test creds: test@gmail.com, secret

**Comment by faturachmanyusup** [comment]
will you let me solve it ?

**Comment by DavidGolodetsky** [comment]
actually I did it. Now deploying it so you  wouldn't be blocked

**Comment by DavidGolodetsky** [comment]
But while I was doing it I noticed a password validation bug. You can take it over if you want. Let me create an issue first

**Comment by DavidGolodetsky** [comment]
Oh, nope password validation is fine.

**Comment by DavidGolodetsky** [comment]
You can take that if you want
https://github.com/DavidGolodetsky/GeekScore-2/issues/21

**Comment by faturachmanyusup** [comment]
thanks, im on my way.
