### ISSUE TITLE
Game edit dialog, field validation

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#2]
On **Game editing** dialog all fields except "name" shouldn't be required. Currently you cannot save your changes unless you've specified all fields.

**Comment by ruchikamuddinagiri** [comment]
Hey! I would like to work on this. Would the changes be just in the game model?

**Comment by DavidGolodetsky** [comment]
Great! Yes, I can see the bug only on the game model.

**Comment by ruchikamuddinagiri** [comment]
So, as far as I can figure out, the user, coop, favorite and teams fields are required during game creation.
But those fields should be optional during game editing?

**Comment by DavidGolodetsky** [comment]
No, I'm talking about that screen. Sorry If issue description is vague. It's frontend issue. Here only "Name" field should be required, other fields are optional.Those optional fields have validation rule if they were specified, for example if it's a link. But those rule shouldn't be required If the field is empty.
![image](https://user-images.githubusercontent.com/32278933/93186488-5fc97b80-f747-11ea-985f-472e3ff25b32.png)

**Comment by fdgenie** [comment]
i can take this one

**Comment by DavidGolodetsky** [comment]
You're on fire)

**Comment by DavidGolodetsky** [comment]
fixed by https://github.com/DavidGolodetsky/GeekScore-2/pull/17
