### ISSUE TITLE
Fix Team cooperative switcher

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#22]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
When creating a team, switch `cooperative` to true

![image](https://user-images.githubusercontent.com/32278933/94789966-4fb7ca00-03de-11eb-9d0d-3af5dbc05c01.png)

### Expected Behavior
You can switch `cooperative` back to false

### Actual Behavior
Switcher disapears

**Comment by fdgenie** [comment]
im on it :)

**Comment by DavidGolodetsky** [comment]
Fixed by
