### ISSUE TITLE
Error when deleting the only existing item

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#25]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
If you have only one game, delete it. Then see the error in the alert popup.

![image](https://user-images.githubusercontent.com/32278933/94793337-fef6a000-03e2-11eb-9d53-b5f47cf6c5f4.png)

### Expected Behavior
No error

### Other Comments
Might be also actual for teams and rounds

**Comment by sixpathdev** [comment]
I'll look into this. I created a PR recently though

**Comment by sixpathdev** [comment]
@DavidGolodetsky  how is the game deleted?... Do I need to fill those fields?

Also, I feel the delete feature should stand on its own though

**Comment by sixpathdev** [comment]
I just tried it now, I don't see an error after deleting

**Comment by DavidGolodetsky** [comment]
> @DavidGolodetsky how is the game deleted?... Do I need to fill those fields?
> 
> Also, I feel the delete feature should stand on its own though

No, you don't need to fill those fields now. It was fixed recently, have you pulled the latest changes?

**Comment by DavidGolodetsky** [comment]
> Also, I feel the delete feature should stand on its own though

Yeah I thought about that, but I don't know how better to design that. Do you have some ideas about that?

**Comment by sixpathdev** [comment]
A simple one though. on the list of cards displayed you could just add the icon there, making it easy to delete

**Comment by DavidGolodetsky** [comment]
Well yeah, but it'll take additional space on mobile screen. And I feel like deletion is not that frequent operation, and it should be harder to delete, cause than all your game history gone.

**Comment by sixpathdev** [comment]
using the position attribute it would sit on the thumbnail in each game listed. I don't see any space it takes there though. Just an additional icon, that's all

**Comment by DavidGolodetsky** [comment]
You mean like this? 
![Uploading image.png…]()

**Comment by DavidGolodetsky** [comment]
About the error, you're right it's not actual, I can see it only on my local machine but it's fine on prod

**Comment by sixpathdev** [comment]
I meant placing the delete icon on the bottom-left corner of the thumbnails

**Comment by sixpathdev** [comment]
opposite the heart icon or close to the heart icon

**Comment by DavidGolodetsky** [comment]
@fdgenie what do you think?

**Comment by fdgenie** [comment]
Ye i think it's a good idea, and to avoid accident delete maybe it can have some confirmation like type the title of the game.

**Comment by DavidGolodetsky** [comment]
Okay, then I'll create an issue about it. Thanx @sixpathdev for the idea!

**Comment by DavidGolodetsky** [comment]
https://github.com/DavidGolodetsky/GeekScore-2/issues/29
