### ISSUE TITLE
Team delete bug 

### ISSUE THREAD

**Issue by fdgenie** [DavidGolodetsky/GeekScore-2#28]
When you delete more than one team without refreshing it doesn't update the state propably. The delete happen but its doesnt appear until you refresh the page.

To reproduce:
1. Create 3 teams
2. Delete 1 team
3. Delete 2 team

**Comment by DavidGolodetsky** [comment]
Nice catch! Should I assign you on this?

**Comment by DavidGolodetsky** [comment]
Probably now you can assign it yourself:)

**Comment by fdgenie** [comment]
yes i will assign me :) thanks
