### ISSUE TITLE
Remove turn option for cooperative games

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#30]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
Create team with cooperative option 
![image](https://user-images.githubusercontent.com/32278933/94806392-8a2d6100-03f6-11eb-8c9b-66cd0cc47ebe.png)

### Expected Behavior
There is no `First turn` option, since it doesn't make sense in cooperative game.

### Actual Behavior
![image](https://user-images.githubusercontent.com/32278933/94806584-e2646300-03f6-11eb-9ac3-312b43121ed0.png)

**Comment by fdgenie** [comment]
i will get that
