### ISSUE TITLE
Setup the project for first time.

### ISSUE THREAD

**Issue by adsingh14** [DavidGolodetsky/GeekScore-2#31]
It would be great if we have a first-time setup tutorial included in this project. Where do we install new modules, dependencies etc ?

**Comment by DavidGolodetsky** [comment]
Agreed. Thanx for feedback, I'll take a look at this.

**Comment by adsingh14** [comment]
Have you created that file ? I'm still an assignee for this project task.

**Comment by adsingh14** [comment]
1. Do you want to move the delete button to popup (including it's functionality) ?
2. I've not worked with Vue. So, It will take some time to complete.

**Comment by DavidGolodetsky** [comment]
No problem, take your time. If you want you can take some other issue to accustom to the project and Vue. I'll provide detailed documentation to the issue.

**Comment by DavidGolodetsky** [comment]
Check out Readme contributions guid.  If you think like I missed something, please let me know.

**Comment by adsingh14** [comment]
Got an error in front end. 
![image](https://user-images.githubusercontent.com/35252877/94990764-3b213080-059c-11eb-9754-830660070ed7.png)

Vue CLI version - **@vue/cli 4.5.6**

**Comment by adsingh14** [comment]
Got an error in client folder.
![image](https://user-images.githubusercontent.com/35252877/94990852-a0752180-059c-11eb-9639-aeb4798b0d5b.png)

Using **vue/cli 4.5.6**

**Comment by DavidGolodetsky** [comment]
sorry, forgot that. Run npm i in the client folder, also I've updated readme file
