### ISSUE TITLE
General fixes for discussion

### ISSUE THREAD

**Issue by fdgenie** [DavidGolodetsky/GeekScore-2#32]
First, i think the store need to be more abstract. What i mean is that there should be a store for crud operation so it doesnt get repeat for store like(games, teams, etc)

Second, its good for every component, page etc to have a name in the script section for debug purposes.

Third, there is no need to have 3 mapgetters in the components, you can have 1 mapgetters with all that you want inside.

**Comment by DavidGolodetsky** [comment]
Thanx for a feedback!
1. Well, maybe it's a matter of taste. Now it has 3 modules for 3 hierarchical entity (games, teams, rounds). Each module consist of CRUD operation related to the entity, but also other operations related to that. For now I don't think it make sense to change it. But as application would grow it should be taken to consideration.
2. Go for it if you need that, I'm using Vue devtool and never encountered such problem.
3. I didn't know it's possible. Go for it and also could you point to the place where you encountered that?

**Comment by fdgenie** [comment]
1. I think its about writing less code in this one rather than matter of taste. I mean you should write one time crud operations that every module will inherit. I think that if you write some piece of code more than 2-3 times you should make one abstract component for the places you need it. But i guess you are write, maybe it need for the application to grow for something like that.

3. For example in TeamDetails.

4. I will add one more. Components maybe need to be seperated in folders like cards, inputs, forms etc, maybe in the future too?

**Comment by DavidGolodetsky** [comment]
2(3 before). ah I see. 
`    ...mapGetters('teams', ['getTeam']),
    ...mapGetters('games', ['getGame']),
    ...mapGetters('rounds', ['getRounds'])`
Here mapGetters takes module as a first parameter and array of getters as a second. How would you improve that?

**Comment by DavidGolodetsky** [comment]
1. Well yeah, you right. It has some repetition. For example here:
![image](https://user-images.githubusercontent.com/32278933/94817845-1e52f480-0406-11eb-98ca-03901632a635.png)

Still I'd rather left modules divided by hierarchy entities (games, teams, rounds) for specific logic. But it make sense to make a separete `crud` module where we could abstract such stuff.

**Comment by DavidGolodetsky** [comment]
3. I followed official [styleguide](https://vuejs.org/v2/style-guide/#Component-files-strongly-recommended) on that. I don't remember where, but it suggest to put all components in one folder and structure them logically by name for better navigation and access experience. I'm not 100% sure about it for now. But for now I think it's fine

**Comment by DavidGolodetsky** [comment]
2. fixed by https://github.com/DavidGolodetsky/GeekScore-2/pull/36

**Comment by DavidGolodetsky** [comment]
created a dedicated discussion for the first issue 
https://github.com/DavidGolodetsky/GeekScore-2/discussions/105
