### ISSUE TITLE
Show Game name in the header

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#34]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
1. Select a game, see the header.
2. Refresh the page

![image](https://user-images.githubusercontent.com/32278933/94812543-8ce08400-03ff-11eb-8c33-6431cb2c1975.png)

![image](https://user-images.githubusercontent.com/32278933/94813189-5bb48380-0400-11eb-8a03-b0a5bf1c35b1.png)

### Expected Behavior
Header is updated without refreshing the page

**Comment by flitzmare** [comment]
hey, i'd like to give it a try :)

**Comment by DavidGolodetsky** [comment]
Great! Good luck:)
