### ISSUE TITLE
Add ability to add user name

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#40]
### Idea
Add ability to specify user name. So in the future user could use it instead of `Me`

### Implementation Steps

1. Add optional Username field on Sign Up page 

![image](https://user-images.githubusercontent.com/32278933/94913893-b9090d00-04b2-11eb-970f-a8ae936d188d.png)

2. Store username in Mongo db for later usage (for that check out how storing user email works)

**Comment by grvsood** [comment]
lemme work on this

**Comment by DavidGolodetsky** [comment]
Sure, good luck!
