### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#41]
### Idea
Create Profile page, where user can see profile info (and later - statistics)

### Implementation Steps

1. Create a page

![image](https://user-images.githubusercontent.com/32278933/94988164-f1bceb00-0573-11eb-85ef-29e73634fe29.png)

2. Make sure to add it to the navbar for mobile version

![image](https://user-images.githubusercontent.com/32278933/94913669-54e64900-04b2-11eb-989a-bb9cbcbc0728.png)

3. On that page display page title (Profile) and username, that could be fetched by user id. Also add the ability to change username

**Comment by maruthimohan** [comment]
Hey @DavidGolodetsky , could I give it a try?

**Comment by DavidGolodetsky** [comment]
Sure, good luck:)

**Comment by DavidGolodetsky** [comment]
I've updated the issue a bit. Ping me if you have any questions

**Comment by DavidGolodetsky** [comment]
Closed by https://github.com/DavidGolodetsky/GeekScore-2/pull/59
