### ISSUE TITLE
Create new node.js route to fetch user by id

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#48]
### Idea
Instead of fetching all existing users and filtering them out on frontend, create a new node.js route to fetch user by id with MongoDB

### Implementation Steps
1. Go to the file` GeekScore-2/client/src/store/modules/user.js`, on the `signInUser` action see that we're fetching all existing users in our db and then filtering them out by id (line 40). 
2. Go to` GeekScore-2/routes/api/users.js` and create new route to fetch user by id. 
3. Use this new route in case of the first step in ` GeekScore-2/client/src/store/modules/user.js`

**Comment by siddhu890** [comment]
Hey, I am willing to contribute can you assign me this open issues.

**Comment by Leos1113** [comment]
I alreay done a pr for this! Sorry I don't read anywhere that they need to assign the issue :(

https://github.com/DavidGolodetsky/GeekScore-2/pull/49

**Comment by DavidGolodetsky** [comment]
yeah, the best practice is to get assigned first in order to notify other developers. Also you won't get Contributor badge if you weren't assign to the issue, though you made a PR

**Comment by DavidGolodetsky** [comment]
Fixed by https://github.com/DavidGolodetsky/GeekScore-2/pull/49
