### ISSUE TITLE
Load user on refresh

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#50]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
After signing in the app, hit refresh and see that navbar items have disappeared, because the app don't know user anymore (though it has userID in localStorage so it can still query it's info).

![image](https://user-images.githubusercontent.com/32278933/95017504-4f2f6580-0662-11eb-8897-3db35541762f.png)

### Expected Behavior
After refreshing the app, I queries user by userID and stores it (object with id and username) in Vuex users module. Navbar items are still there after refresh. 

###Other comments
You can plase loading user call in the `App.vue` component, as it's the root component of the app. You would need to create new action in Vuex that would query user by Id. In that action you would need to use `/api/users/:id` node.js route. See example of calling that route in `signInUser` action.

**Comment by BerniWittmann** [comment]
@DavidGolodetsky Sorry, did not notice, that one should be assigned to the issue first. Nevertheless the code for this is in #52
