### ISSUE TITLE
Create a Node.js route for calculating win rate

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#53]
### Idea
Win rate is the percent of games(rounds) that you won. We would like to show win rate per game (e.g. how often do you win in Carcassonne? - 34% of played games). In Geek Score we can calculate such measurement, because games consist of teams and in every team you can find user, currently it's "Me" player (In the future Me will be replaced by username). After that we'll show win rate on Profile page, which is on the way.

### Implementation Steps
Create a new route in `GeekScore-2/routes/api/users.js ` which would fetch all games and teams then calculate win rate of the user per game, filtering it out by Me player.

**Comment by Thunder80** [comment]
Can a work on this?

**Comment by DavidGolodetsky** [comment]
Sure thing. Ping me if you need any additional info and good luck!
