### ISSUE TITLE
Create a tendency chart 

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#58]
### Idea
Each round has info about date when it occur. Using this info we could build a tendency chart like this one: 

![image](https://user-images.githubusercontent.com/32278933/95499844-8e392000-09ae-11eb-9c80-6f2295558e36.png)

### Implementation Steps
Try to use [vue-chart](https://vue-chartjs.org/guide/#introduction) library for this purpose, cause we're already using it for `statistics` chart. If you can't use it, then check out this [library](https://dmtrbrl.github.io/vue-trend-chart/). 
You can place new chart as a new tab `Tendency` 

![image](https://user-images.githubusercontent.com/32278933/95500240-35b65280-09af-11eb-92ab-e9202b24fe0b.png)

**Comment by Rayleigh3105** [comment]
Hey, can I tackle this issue? If so please assign the Ticket to me :D

**Comment by DavidGolodetsky** [comment]
Sure!

**Comment by Rayleigh3105** [comment]
Hey, which Icons do you use?

**Comment by DavidGolodetsky** [comment]
@Rayleigh3105  for the tab? I'm looking here https://materialdesignicons.com/
and I think of `chart-line` or `chart-bell-curve-cumulative`. But you can provide what you think suits the best

**Comment by DavidGolodetsky** [comment]
so you can use anything from this link, just prefix it with `mdi-`

**Comment by Rayleigh3105** [comment]
Ah, okay. Never used Vue.js before (only Angular), I think its better to have basics in a Framework, where I want to implement something :D. That issue is a little bit to big for me, may you dissociate the issue, sorry?

**Comment by DavidGolodetsky** [comment]
sure, np:) if you want to learn more about Vue I'd recommend those resources:

-  https://www.vuemastery.com
- https://vueschool.io/
- https://michaelnthiessen.com/
