### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#6]
Simple docker config would be great. It should be able to start server, start client and run tests.

**Comment by Rayleigh3105** [comment]
Hey,
so you want a docker-compose file to startup your Project, is that correct?

**Comment by DavidGolodetsky** [comment]
Hi, @Rayleigh3105! Yes, nothing special, just basic implementation of docker, so it would be easier to unfold the project on different machines. I've done something similar here in the first version of the [app], but I'm not sure if it's correct, I'm just learning docker. 
(https://github.com/DavidGolodetsky/GeekScore-1)

**Comment by Rayleigh3105** [comment]
I think I Van help you out.

**Comment by Rayleigh3105** [comment]
Hey, can you assign the Ticket to me?

**Comment by Rayleigh3105** [comment]
The compose file I´m creating, will not work for windows. The reason for this are mount binds for the database data which are getting stored on the host. 
Is it necessary to store data permanent on the host? Or is this docker-compose file only for development purpose?

**Comment by DavidGolodetsky** [comment]
yeah, it's fine, development purpose is first. If anything, it'll be improved later if it's needed.

**Comment by Rayleigh3105** [comment]
I´m getting an error when pushing a new branch to this repo.
remote: Permission to DavidGolodetsky/GeekScore-2.git denied to Rayleigh3105.
fatal: unable to access 'https://github.com/DavidGolodetsky/GeekScore-2.git/': The requested URL returned error: 403
00:53:17.565: [GeekScore-2] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/docker:docker --set-upstream
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/DavidGolodetsky/GeekScore-2.git/'

Can you give me write access?

**Comment by DavidGolodetsky** [comment]
You don't need to have any specific access in order to create PR. You need to fork the repo, create a branch in your repo, push everything there and create a PR from this branch to my master. More info here: https://github.com/acmbvp/Hacktoberfest#2-star-and-fork-this-repository

**Comment by DavidGolodetsky** [comment]
Also, I've updated Readme contributions guid.

**Comment by Rayleigh3105** [comment]
PR is made -> https://github.com/DavidGolodetsky/GeekScore-2/pull/56
