### ISSUE TITLE
List all user games win rate on Profile page

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#61]
###Idea
When Profile page is ready (almost there), create a component there which would list all games win rate.

###Implementation steps
There is an action `loadWinRate` which loads all games win rate as an object where key is a game name and value is user win rate. You need to call this action on Profile page and use its state result in your component. Component should be as a simple list with title "Win Rates". List should be in 2-3 columns for bigger screens and as 1 column for mobile devices.

**Comment by mihailot01** [comment]
I think I can do it, can you assign me?

**Comment by DavidGolodetsky** [comment]
@mihailot01  Hi, it's already done, sorry forgot to move the ticket.

**Comment by DavidGolodetsky** [comment]
@mihailot01 you can take a look at [Project](https://github.com/DavidGolodetsky/GeekScore-2/projects/1#card-47223757) kanban and see if there anything interesting for you `in To do` list. Contact me if you need more info on the topic or if you want me to create a new issue
