### ISSUE TITLE
Enable Live-reload on Docker

### ISSUE THREAD

**Issue by DavidGolodetsky** [DavidGolodetsky/GeekScore-2#63]
### Environment
Browsers: Chrome 
OS: Mac OS

### Steps to reproduce
1. Build the app using `docker-compose up --build`
2. Change some code to see it on the screen
3. Reload the page
4. Close your docker process and restart it with `docker-compose up`

### Expected Behavior
Page is live-reloaded

### Actual Behavior
Changes aren't there even after restarting the process with `docker-compose up`

**Comment by DavidGolodetsky** [comment]
@Rayleigh3105 maybe you could give some advice on that?

**Comment by Rayleigh3105** [comment]
Sure, didnt know that should also work. This should be not a bug more a feature 😀

**Comment by DavidGolodetsky** [comment]
agreed:)

**Comment by redpfire** [comment]
I can work on this one :)

**Comment by redpfire** [comment]
Please review the PR and let me know if I have to commit any changes :)

**Comment by DavidGolodetsky** [comment]
Thank you, @redpfire

**Comment by DavidGolodetsky** [comment]
Works great! Can it be done for backend as well? I can create a separate issue if needed

**Comment by redpfire** [comment]
I didn't really look into your backend but i'll take a look

**Comment by redpfire** [comment]
You actually have it set up it seems.
