### ISSUE TITLE
Enable live-reload for the backend

### ISSUE THREAD

**Issue by redpfire** [DavidGolodetsky/GeekScore-2#65]
Referenced in #63

In your `package.json` you have two scripts:
```json
"scripts": {
    "serve": "nodemon server.js",
    "start": "node server.js"
},
```
It seems like `nodemon` provides a live functionality. In your server's `Dockerfile` you actually do this:
```
# Serve the app
CMD ["node", "server.js"]
```
which is counterintuitive because you already have it set up.
The fix is minor and I'll provide a PR soon.

**Comment by DavidGolodetsky** [comment]
Indeed

**Comment by redpfire** [comment]
Seems like I have to do the same trickery with the source code as in frontend to make it work. Working on that :)
